### PR TITLE
PHP 7 support

### PR DESCRIPTION
**Pull request by Danack**
It is not pretty, but this PR adds support for PHP 7.

All the tests pass, but it ought to be tested against some real use cases.

### CODE REVIEW

**Comment by nrk** [comment]
Thanks @Danack! I'm really sorry for my late reply, I'm so busy with various things lately that I can hardly manage to comment on issues and PRs on GitHub which is very bad. The good news is that by the end of May I should finally be able to return to a normal pace and have time for clearing the backlog and resume working on open source projects. I'll try my best to get some things in before that date, but currently I can't guarantee anything :-(

That said your PR is particularly appreciated as I still have to test basically everything on PHP 7. And there's even a build environment on TravisCI now, great!

**Comment by nrk** [comment]
Hi @Danack I finally had time to test your PR (I'm ashamed for the long wait :sob: sorry) and spotted a memory leak when using PHP __7.0.0beta1__, but oddly enough everything looks fine with PHP 5.6.9. I'll try to investigate the leak by myself but in the meanwhile I took the chance to publish [a gist](https://gist.github.com/nrk/b077030cd19691955144) with everything needed to easily set up the same scripts that I'm using to reproduce the issue.

This is the output of the above mentioned scripts where you can see the leak ([more details](https://gist.github.com/nrk/b077030cd19691955144#file-readme-md)):

```
Running monitor script on PHP 7.0.0beta1
Used memory after 10000 events: 2616280 (increment 2616280) bytes.
Used memory after 20000 events: 4536280 (increment 1920000) bytes.
Used memory after 30000 events: 6456280 (increment 1920000) bytes.
Used memory after 40000 events: 8376280 (increment 1920000) bytes.
Used memory after 50000 events: 10296280 (increment 1920000) bytes.
Used memory after 60000 events: 12216280 (increment 1920000) bytes.
Used memory after 70000 events: 14136280 (increment 1920000) bytes.
Used memory after 80000 events: 16056280 (increment 1920000) bytes.
Used memory after 90000 events: 17976280 (increment 1920000) bytes.
Used memory after 100000 events: 19896280 (increment 1920000) bytes.
```

```
Running monitor script on PHP 5.6.9
Used memory after 10000 events: 749320 (increment 749320) bytes.
Used memory after 20000 events: 749544 (increment 224) bytes.
Used memory after 30000 events: 749544 (increment 0) bytes.
Used memory after 40000 events: 749544 (increment 0) bytes.
Used memory after 50000 events: 749544 (increment 0) bytes.
Used memory after 60000 events: 749544 (increment 0) bytes.
Used memory after 70000 events: 749544 (increment 0) bytes.
Used memory after 80000 events: 749544 (increment 0) bytes.
Used memory after 90000 events: 749544 (increment 0) bytes.
Used memory after 100000 events: 749544 (increment 0) bytes.
```

**Comment by Danack** [comment]
You should be able to locate where the mem leak is either by running the script through valgrind with the zend memory allocator disabled like:

    valgrind php -d USE_ZEND_ALLOC=0 testScript.php

Or by compiling a debug version of PHP, which has checks for memory leaks built in. 

I'm a little busy right now, so if you can't find it, I might be able to investigate towards the end of the week.
 
> I finally had time to test your PR (I'm ashamed for the long wait :sob: sorry)

Pfft. It's the same year, and PHP 7 hasn't shipped, so it's no big deal. It's not like we have to buy [a cake for it yet](https://www.youtube.com/watch?v=oAiVsbXVP6k).

**Comment by Red-wolf-s-husband** [comment]
Any progress ? where is the author and the author? going to born a baby again?

**Comment by nrk** [comment]
@Red-wolf-s-husband I fixed most of the leaks in @Danack's code except one but I'm currently busy with both daytime work and life. Feel free to contribute some code in the form of a new pull request if you require phpiredis to be compatible with PHP 7.0 ASAP. Thanks!

**Comment by Red-wolf-s-husband** [comment]
@nrk Ok, But I have a question here,  I didn't see any of your pull request of Danack's repo. How did you fixed that :question:

**Comment by RustJason** [comment]
https://github.com/Danack/phpiredis/pull/1 this will fix those memory leaks

**Comment by ProPheT777** [comment]
Any progress on that?

**Comment by together-networks** [comment]
:+1:  for fixing memory leak and adding php7 support
Great job guys! Just finish it please :)

**Comment by bocharov** [comment]
:+1: for fixing memory leak and adding php7 support
Great job guys! Just finish it please :)

**Comment by homeyjd** [comment]
+1

**Comment by enryold** [comment]
+1 for merging into master :)

**Comment by ovr** [comment]
Any news?

**Comment by nrk** [comment]
@ovr in a couple of weeks I should be able to find the time for phpiredis, anyway the problem is not only pushing a fix for the library to work on PHP 7 but also deciding how to handle the split between PHP 5 and PHP 7 (I'm not really a fan of those `#ifdef`, but the codebase is not big enough to justify a separate branch just for that), and finally pushing an actual and "official" release of the library.

**Comment by rchunping** [comment]
@nrk thanks, waiting for that.

**Comment by nrk** [comment]
I'm closing this PR as it's been merged and used as base for the further developments on the `php7` branch. Please head to #50 for details. Thanks @Danack!

**Pull request closed without merging**
